name: Delete portfoglio
on:
  workflow_dispatch:
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git rm -f dist/assets/portfoglio || true
          git commit -m "Removed file portfoglio" || true
          git push
